// Code generated by "stringer -type=MediaType"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Movie-0]
	_ = x[TV-1]
	_ = x[Other-2]
}

const _MediaType_name = "MovieTVOther"

var _MediaType_index = [...]uint8{0, 5, 7, 12}

func (i MediaType) String() string {
	if i >= MediaType(len(_MediaType_index)-1) {
		return "MediaType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MediaType_name[_MediaType_index[i]:_MediaType_index[i+1]]
}
